### ISSUE TITLE
Geometry is split

### ISSUE THREAD

**Issue by DavidPeicho** [mattatz/unity-mesh-smoothing#2]
Nice work, thanks. I haven't yet read the code, but basically the geometry might be split into multiple parts:

![image](https://user-images.githubusercontent.com/8783766/143275222-fd814806-1569-4b0e-bc9b-0f9f5a573d02.png)

I will have a look and maybe do a PR.

**Comment by DavidPeicho** [comment]
Turns out Unity can duplicate vertices, which makes sense because of vertex atttributes. The obvious solution then is to add more connection (using `VertexConnection`) for "duplicate", i.e., vertices at the same position with some small delta.

**Comment by mr-lab** [comment]
and how do we do that ?
